name: Lotto 6/45 result checker

on:
  schedule:
  - cron: 0 12 * * 0 # every Sunday on 09:00 PM (KST)
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check result
      uses: chaeyk/lottery-check-action@v1
      with:
        username: ${{ secrets.DHL_USERID }}
        password: ${{ secrets.DHL_PASSWORD }}
        telegram-bot-token: ${{ secrets.TLG_BOTTOKEN }}
        telegram-chatid: ${{ secrets.TLG_CHATID }}
        lottery-code: lo40
